### ISSUE TITLE
gulp-ng-annotate appears to be destroying previous sourcemaps

### ISSUE THREAD

**Issue by OverZealous** [Kagami/gulp-ng-annotate#9] opened 2014-10-08 20:47 UTC
I can tell you've already had a bunch of fun with sourcemaps, so I hate to bring this up.  However, I have a script that, among other things, passes the files through [gulp-6to5](https://www.npmjs.org/package/gulp-6to5), then through gulp-ng-annotate.

If I leave ng-annotate in-place, I *only* get sourcemaps showing the changes from ng-annotate, as if the original source was the output from 6to5.  If I remove ng-annotate, I clearly see the source map from 6to5.  For some reason, ng-annotate is clobbering the sourcemap.

I've removed all extra steps to verify the issue occurs with 6to5.  Obviously, since 6to5 is an ES6 compiler, and ng-annotate does not understand ES6 code, I cannot reverse the order to see if there is still an error.

**Comment by amcdnl** [comment] 2015-01-30 14:25
It would be nice if we could mute these messages - http://www.screencast.com/t/p0WzZKMl

**Comment by Kagami** [comment] 2015-01-30 14:36
@amcdnl yeap, good catch. I've just published `gulp-ng-annotate` 0.5.1 with `gulpWarnings` option. If you set it to false this warning won't be shown anymore.
Thanks!

**Comment by Kagami** [comment] 2015-01-30 14:48
Also it was a minor bug with relative path comparision on Windows caused by #14. So in your case warnings shouldn't be shown anymore at all.

**Comment by wilsonjackson** [comment] 2015-05-03 03:46
I don't know if the problem I'm seeing is related to this issue, but when I add `gulp-ng-annotate` to my gulp build after `gulp-typescript`, the resulting map includes filenames with both `.ts` and `.js` extensions, effectively duplicating every source file. E.g., `{"version":3,"sources":["app.ts","app.js"]...` Without `gulp-ng-annotate`, it contains only `.ts` extensions, as it should.

It looks like @vitalybe's sample repo exhibits the same behavior. If it's not related to this issue, should I open a new one, or is this just down to something I'm doing wrong?

**Comment by wilsonjackson** [comment] 2015-05-03 03:47
btw I'm on a Mac, so it's not a Windows path thing.

**Comment by Kagami** [comment] 2015-05-03 03:51
@wilsonjackson please open a new issue. I should have done that previous time (because @vitalybe issue was irrelevent to this one, to be honest), but forgot about it.

**Comment by wilsonjackson** [comment] 2015-05-03 04:15
@Kagami Thanks for the quick reply, I've submitted #25 with a sample repo.

**Comment by Kagami** [comment] 2015-05-03 05:38
Closing this issue because it became too messy. Seems like the only problem regarding sourcemaps still exists is the extra intermediate sources. Moving discussion on this to #25.

**Closed by Kagami** 2015-05-03 05:38 UTC
